//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorTabernaclChoir.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorTabernaclChoir.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Accompanist.
        /// </summary>
        public static string AboutAccompanist {
            get {
                return ResourceManager.GetString("AboutAccompanist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Musical Director.
        /// </summary>
        public static string AboutMusicalDirector {
            get {
                return ResourceManager.GetString("AboutMusicalDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Choir.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administration.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string ContactInvalidEmailAddress {
            get {
                return ResourceManager.GetString("ContactInvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ContactSubmit {
            get {
                return ResourceManager.GetString("ContactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting the Choir.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string GalleryImageCaption {
            get {
                return ResourceManager.GetString("GalleryImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Gallery/{0}.jpg.
        /// </summary>
        public static string GalleryImageUrl {
            get {
                return ResourceManager.GetString("GalleryImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. We apologise for any inconvenience. If  this error persists please contact us..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanist.
        /// </summary>
        public static string HomeAccompanist {
            get {
                return ResourceManager.GetString("HomeAccompanist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Director.
        /// </summary>
        public static string HomeMusicalDirector {
            get {
                return ResourceManager.GetString("HomeMusicalDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditions.
        /// </summary>
        public static string JoinAuditions {
            get {
                return ResourceManager.GetString("JoinAuditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerts.
        /// </summary>
        public static string JoinConcerts {
            get {
                return ResourceManager.GetString("JoinConcerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string JoinLocation {
            get {
                return ResourceManager.GetString("JoinLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehearsal Times.
        /// </summary>
        public static string JoinRehearsalTimes {
            get {
                return ResourceManager.GetString("JoinRehearsalTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string JoinSubscriptions {
            get {
                return ResourceManager.GetString("JoinSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining the Choir.
        /// </summary>
        public static string JoinTitle {
            get {
                return ResourceManager.GetString("JoinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string MenuJoin {
            get {
                return ResourceManager.GetString("MenuJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string MenuRecordings {
            get {
                return ResourceManager.GetString("MenuRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string MenuVisits {
            get {
                return ResourceManager.GetString("MenuVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string MenuWorks {
            get {
                return ResourceManager.GetString("MenuWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem saving your changes.
        /// </summary>
        public static string MessageTextSaveError {
            get {
                return ResourceManager.GetString("MessageTextSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes were saved.
        /// </summary>
        public static string MessageTextSaveSuccess {
            get {
                return ResourceManager.GetString("MessageTextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageTitleError {
            get {
                return ResourceManager.GetString("MessageTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageTitleSuccess {
            get {
                return ResourceManager.GetString("MessageTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Director.
        /// </summary>
        public static string MusicalDirector {
            get {
                return ResourceManager.GetString("MusicalDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published {0:dd/MM/yyyy}.
        /// </summary>
        public static string NewsPublished {
            get {
                return ResourceManager.GetString("NewsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Images/Posts/{0}.jpg.
        /// </summary>
        public static string PostImageUrl {
            get {
                return ResourceManager.GetString("PostImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our YouTube channel.
        /// </summary>
        public static string RecordingsLinkText {
            get {
                return ResourceManager.GetString("RecordingsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published {0:dd\/MM\/yyyy} at {0:HH\:mm}.
        /// </summary>
        public static string RecordingsPublished {
            get {
                return ResourceManager.GetString("RecordingsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can listen to some recordings of the choir. For more please visit .
        /// </summary>
        public static string RecordingsText {
            get {
                return ResourceManager.GetString("RecordingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string RecordingsTitle {
            get {
                return ResourceManager.GetString("RecordingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string SidebarLatestNews {
            get {
                return ResourceManager.GetString("SidebarLatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string SidebarLinks {
            get {
                return ResourceManager.GetString("SidebarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see all news.
        /// </summary>
        public static string SidebarNewsLink {
            get {
                return ResourceManager.GetString("SidebarNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no performances scheduled for the near future..
        /// </summary>
        public static string SidebarNoEvents {
            get {
                return ResourceManager.GetString("SidebarNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string SidebarUpcomingEvents {
            get {
                return ResourceManager.GetString("SidebarUpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Social Media Link.
        /// </summary>
        public static string SocialMediaAddTitle {
            get {
                return ResourceManager.GetString("SocialMediaAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Social Media Link.
        /// </summary>
        public static string SocialMediaDeleteTitle {
            get {
                return ResourceManager.GetString("SocialMediaDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Social Media Link.
        /// </summary>
        public static string SocialMediaEditTitle {
            get {
                return ResourceManager.GetString("SocialMediaEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/SocialMedia/{0}.png.
        /// </summary>
        public static string SocialMediaImageUrl {
            get {
                return ResourceManager.GetString("SocialMediaImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our {0} page.
        /// </summary>
        public static string SocialMediaTextFormat {
            get {
                return ResourceManager.GetString("SocialMediaTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Links.
        /// </summary>
        public static string SocialMediaTitle {
            get {
                return ResourceManager.GetString("SocialMediaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cymraeg.
        /// </summary>
        public static string SwitchLanguageLabel {
            get {
                return ResourceManager.GetString("SwitchLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridgend Tabernacl Choir.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Visits.
        /// </summary>
        public static string VisitsTitle {
            get {
                return ResourceManager.GetString("VisitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major choral works performed by the choir since 2001:.
        /// </summary>
        public static string WorksText {
            get {
                return ResourceManager.GetString("WorksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string WorksTitle {
            get {
                return ResourceManager.GetString("WorksTitle", resourceCulture);
            }
        }
    }
}
